### ISSUE TITLE
__del__ error during unit tests

### ISSUE THREAD

**Issue by Kris-0605** [Kris-0605/fernet_files#4]
Currently, unit tests are passing.
However, the following error is happening repeatedly:
```
Exception ignored in: <function FernetFile.__del__ at 0x7efc9cb65bc0>
Traceback (most recent call last):
  File "/home/runner/work/fernet_files/fernet_files/fernet_files/__init__.py", line 236, in __del__
    self.close()
  File "/home/runner/work/fernet_files/fernet_files/fernet_files/__init__.py", line 221, in close
    if isinstance(self.__file, BytesIO):
                  ^^^^^^^^^^^
AttributeError: 'FernetFile' object has no attribute '_FernetFile__file'
```
I've been unable to re-create this in the console so far, and I may have to change the attribute to no longer be private, however I have not yet figured out why this is an issue. More investigation required.

**Comment by Kris-0605** [comment]
This error message occurs when something goes wrong with the `fernet_files.FernetFile.__init__` function. An `except` statement has now been added to `fernet_files.FernetFile.close()` to catch `AttributeError`, meaning this error message is no longer present.
